### ISSUE TITLE
Create hdfs fails 

### ISSUE THREAD

**Issue by mohiuddinopu** [gdgt/cmapi#1]
Hi, 
First of all, thanks for sharing this awesome approach. I am running in RHEL 6.5 and seeing the following error. It initiated a cdh5.9 cluster. Probably some property name needs to be updated. 

> HDFS
Create hdfs service
Traceback (most recent call last):
  File "/root/cmxDeploy.py", line 1922, in <module>
    main()
  File "/root/cmxDeploy.py", line 1871, in main
    setup_hdfs()
  File "/root/cmxDeploy.py", line 207, in setup_hdfs
    service_config = cdh.dependencies_for(service)
  File "/root/cmxDeploy.py", line 1573, in dependencies_for
    for k, v in service.get_config(view="full")[0].items():
  File "/usr/lib/python2.6/site-packages/cm_api/endpoints/services.py", line 521, in get_config
    return self._parse_svc_config(resp, view)
  File "/usr/lib/python2.6/site-packages/cm_api/endpoints/services.py", line 138, in _parse_svc_config
    svc_config = json_to_config(json_dic, view == 'full')
  File "/usr/lib/python2.6/site-packages/cm_api/endpoints/types.py", line 1282, in json_to_config
    config[k] = ApiConfig.from_json_dict(entry, None)
  File "/usr/lib/python2.6/site-packages/cm_api/endpoints/types.py", line 288, in from_json_dict
    obj._set_attrs(dic, allow_ro=True)
  File "/usr/lib/python2.6/site-packages/cm_api/endpoints/types.py", line 223, in _set_attrs
    attr = self._check_attr(k, allow_ro)
  File "/usr/lib/python2.6/site-packages/cm_api/endpoints/types.py", line 236, in _check_attr
    (name, self.__class__.__name__))
AttributeError: Invalid property sensitive for class ApiConfig.

**Comment by gdgt** [comment]
Ah! that's because 'sensitive' attribute was added in in v14. 
please update your CM API to cm5-5.9.0 branch

`git clone https://github.com/cloudera/cm_api.git -b cm5-5.9.0 $HOME/cm_api && pip install $HOME/cm_api/python`
